[build]
publish = "dist"
command = "pnpm run build"

[[headers]]
for = "/assets/*.js"
[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.css"
[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/logo.png"
[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/index.html"
[headers.values]
cache-control = "public, max-age=0, must-revalidate"
